apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            # El Workflow reemplazará la siguiente línea con el DNS real del NLB
            proxy_pass http://REEMPLAZAR_CON_DNS_INTERNO_BACKEND;           
            
            # Configuraciones recomendadas para que el proxy pase bien las cabeceras
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Tiempos de espera para evitar que el Gateway se quede colgado
            proxy_connect_timeout 10s;
            proxy_read_timeout 10s;
        }
    }